### ISSUE TITLE
language

### ISSUE THREAD

**Issue by b33fsup3m3** [XDeadHackerX/NetSoc_OSINT#2]
can you update the tool with dif languages like english?

**Comment by XDeadHackerX** [comment]
> can you update the tool with dif languages like english?

It is translated in English

**Comment by b33fsup3m3** [comment]
Oh well thank you, didn’t saw that.

Happy holidays and a good start to the new year I wish you

**Comment by XDeadHackerX** [comment]
I hope you like the tool, happy holidays ;)

**Comment by b33fsup3m3** [comment]
Why do i have to reply to this email directly?
